#define REGISTER_EMAIL_ERROR "Email já existe\n"
#define REGISTER_USER_SUCCESS "Cadastro feito com sucesso\n"
#define REGISTER_POST_SUCCESS "post cadastrado com sucesso\n"
#define LOGIN_ERROR "Email ou senha incorretos,tente novamente\n"
#define USER_EMAIL_LENGHT_ERROR "Email muito grande\n"
#define USER_PASSWORD_LENGHT_ERROR "Senha muito grande\n"
#define POST_LENGHT_ERROR "post muito grande\n"
#define GET_POST_ERROR "post nao existe\n"
#define USERS_FILE "users.txt"
#define POSTS_FILE "posts.txt"
#define USER_PASSWORD_LENGHT_SMALL_ERROR "Senha muito fraca"